#!/bin/bash

if command -v mvn >/usr/ 2>&1; then
    echo "Maven is already installed."
else
    echo "Maven is not installed. Proceeding with installation..."
    # Call your installation script here
    ./maven.sh
fi
